name: Update from Second Repository

on:
  repository_dispatch:
    types:
      - second-repo-push-event

jobs:
  update_from_second_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create branch
        id: branch
        run: |
          git checkout -b second-repo-updates
          echo "::set-output name=branch_name::second-repo-updates"

      - name: Add remote repository
        run: git remote add second-repo remote-repository-url

      - name: Fetch updates
        run: git fetch second-repo

      - name: Merge updates
        run: git merge second-repo/main --no-commit

      - name: Show changes
        run: git diff --name-status HEAD

      - name: Display commit message
        run: echo "Update from Second Repository"

      - name: Set up Git user
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"

      - name: Create commit
        run: git commit -a -m "Update from Second Repository"

      - name: Print branch name
        run: echo "Branch: ${{ steps.branch.outputs.branch_name }}"
